language: java
jdk:
  - oraclejdk8
# Oracle JDK 7 no longer supported, we use env matrix to test various CMM providers
#  - oraclejdk7
# Some JPEGImageReader tests fail on OpenJDK, need to investigate/fix before enabling
#  - openjdk7
env:
  - MAVEN_OPTS=-Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider
  - MAVEN_OPTS=""
cache:
  directories:
  - $HOME/.m2
